name: Upload Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Updated to allow pushing tags

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update version
        id: update-version # Add an ID to reference this step
        run: |
          # Increment version in VERSION file
          IFS='.' read -r major minor patch < VERSION
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "$new_version" > VERSION
          echo "Updating setup.py with version $new_version"
          python -c "import re; f=open('setup.py', 'r+'); content=f.read(); f.seek(0); f.write(re.sub(r'version=\"[0-9]+\.[0-9]+\.[0-9]+\"', f'version=\"$new_version\"', content, count=1)); f.truncate(); f.close()"
          echo "new_version=$new_version" >> $GITHUB_ENV # Store new_version in the environment

      - name: Commit and push version update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION setup.py
          git commit -m "Bump version to latest version"
          git push origin main

      - name: Create and push tag
        run: |
          git tag "v${{ env.new_version }}" # Use the new_version from the environment
          git push origin "v${{ env.new_version }}"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
